[module]

[module.hugoVersion]
min = "0.110.0"

[[module.imports]]
path = "github.com/hugomods/hugopress"

[[module.imports]]
path = "github.com/KaTeX/KaTeX"
[[module.imports.mounts]]
source = "fonts"
target = "assets/mods/katex/fonts"

[params.hugopress.modules.katex.hooks.head-end]
cacheable = true
cache_store_key = "hasKaTeX"
partial = "katex/assets/css"

[params.hugopress.modules.katex.hooks.body-end]
cacheable = true
cache_store_key = "hasKaTeX"
partial = "katex/assets/js"
